version: '3'

services:
  # MCP Candidate Server with HTTP transport
  candidate-mcp-server-http:
    build:
      context: .
    ports:
      - "3000:3000"
    command: ["node", "dist/index.js", "--transport=http", "--port=3000"]
    environment:
      - NODE_ENV=production
    volumes:
      - ./dist:/app/dist

  # MCP Candidate Server with stdio transport (default)
  candidate-mcp-server-stdio:
    build:
      context: .
    environment:
      - NODE_ENV=production
    volumes:
      - ./dist:/app/dist
    # Use default command (npm start) 